export const siteMetadata = {
  title: 'Raavon Group — The Spirit Behind Every Brand',
  titleTemplate: '%s | Raavon Group',
  description:
    'Raavon is a global holding company that builds software products, digital ventures, and technology brands across every industry. One spirit. Many ventures. Built for the world.',
  keywords: [
    'Raavon',
    'Raavon Group',
    'holding company',
    'software studio',
    'digital solutions',
    'technology ventures',
    'software development',
    'product design',
    'mobile applications',
    'web platforms',
    'fintech',
    'AI products',
    'digital brands',
    'global technology company',
    'startup studio',
    'venture builder',
    'Nigeria tech company',
    'African technology',
  ].join(', '),
  url: 'https://raavon.com',
  ogImage: 'https://raavon.com/og-image.png',
  twitterHandle: '@raavongroup',
  locale: 'en_US',
}
